#!/bin/bash

# THIS IS A WORK IN PROGRESS, AND PROBABLY WON'T WORK UNTIL THIS COMMENT IS REMOVED

# Install docker
# * https://docs.docker.com/engine/installation/linux/ubuntulinux/
apt-get update
apt-get install apt-transport-https ca-certificates
apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" > /etc/apt/sources.list.d/docker.list
apt-get update
apt-get purge lxc-docker
# apt-cache policy docker-engine
sudo apt-get install linux-image-extra-$(uname -r) apparmor docker-engine
#sudo service docker start

# Guac server
docker run --name some-guacd -d glyptodon/guacd
# docker logs some-guacd # Confirms it's working

# MySQL
docker run --rm glyptodon/guacamole /opt/guacamole/bin/initdb.sh --mysql > initdb.sql


# Client
docker run --name some-guac-client -d glyptodon/guacamole
# docker logs some-guac-client # Confirms it's working


# Don't know what this is
#docker run --name some-app --link some-guacd:guacd -d application-that-uses-guacd
