#!/bin/bash

# Config
VNCPASS="unsecure"

# Set VNC password
/usr/bin/expect <<EOF
spawn "/usr/bin/vncpasswd"
expect "Password:"
send "$VNCPASS\r"
expect "Verify:"
send "$VNCPASS\r"
expect "Would you like to enter a view-only password (y/n)?"
send "n\r"
exit
EOF
