#!/bin/bash

# Config
VNCPASS="notsecure"

# Set VNC password
/usr/bin/expect <<EOF
spawn "/usr/bin/vncpasswd"
expect "Password:"
send "$VNCPASS\r"
expect "Verify:"
send "$VNCPASS\r"
expect eof
exit
EOF
