#!/bin/bash

# Config
IP=$1

# Copy script to server
scp guacdoc root@$IP:/root/guacdoc

# Make executable on server
ssh root@$IP chmod +x /root/guacdoc

# Run it on server
ssh root@$IP /root/guacdoc

# Connect to server to try stuff
ssh root@$IP
